name: smf_contracts
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  mason: ^0.1.1
  smf_contribution_engine:
    path: ../smf_contribution_engine
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
