name: smf_firebase_analytics
description: Firebase Analytics integration module for SMF projects.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, firebase, analytics, events, measurement]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  smf_contracts: ^0.1.0
  mason: ^0.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
