name: smf_modules
repository: https://github.com/saymyframe/smf_modules
homepage: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues

# All Dart packages in this repository
packages:
  - ./*

# Ignore brick templates and generated mason folders
ignore:
  - "**/__brick__/**"
  - "**/brick/**"
  - "**/bricks/**"
  - "**/mason/**"

command:
  bootstrap:
    # https://github.com/dart-lang/pub/issues/3404
    runPubGetInParallel: false
    hooks:
      # Auto-bundle templates after bootstrap so dev env is ready
      post: melos run bundle
  version:
    # Generate commit links in package changelogs
    linkToCommits: true
    # Additionally build a changelog at the workspace root
    workspaceChangelog: true
    # Do not bump dependents automatically
    updateDependents: false

scripts:
  # Bundle mason bricks in each package that contains a "bricks" directory
  bundle:
    run: |
      melos exec -c 6 --fail-fast --dir-exists="bricks" -- \
        dart $MELOS_ROOT_PATH/tools/bundle_bricks.dart

  # Quality gates
  analyze:
    run: melos exec -c 6 -- dart analyze --fatal-infos --fatal-warnings
  format:
    run: melos exec -c 6 -- dart format . --fix
  format:check:
    run: melos exec -c 6 -- dart format . --output=none --set-exit-if-changed
  test:
    run: melos exec -c 4 --fail-fast -- dart test --reporter expanded
  check:
    run: |
      melos run format:check && \
      melos run analyze && \
      melos run test

  # Release helper (versioning + push tags)
  release:
    run: |
      melos version --yes
      git push --follow-tags
