name: smf_firebase_core
description: Firebase Core integration for SMF Flutter applications with ready-to-use setup templates.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, firebase, integration, configuration, core]

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  smf_contracts:
    path: ../../smf_contracts
  smf_contribution_engine:
    path: ../smf_contribution_engine

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
