name: smf_firebase_core
description: Firebase Core integration for SMF Flutter applications with ready-to-use setup templates.
version: 0.2.1
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [ flutter, firebase ]
license: Apache-2.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  smf_contracts: ^0.2.0
  smf_contribution_engine: ^0.2.0
  mason: ^0.1.1

dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  test: ^1.24.0
