name: smf_go_router
description: GoRouter integration, DSL, and route generators for SMF.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, routing, go-router, navigation, codegen]

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  mason_logger: ^0.3.3
  smf_contracts:
    path: ../../smf_contracts
  smf_contribution_engine:
    path: ../smf_contribution_engine
  mustachex: ^1.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
