name: smf_go_router
description: GoRouter integration, DSL, and route generators for SMF.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, routing, go-router, navigation, codegen]

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  mason_logger: ^0.3.3
  smf_contracts: ^0.1.0
  smf_contribution_engine: ^0.1.0
  mustachex: ^1.0.0
  path: ^1.9.1
  mason: ^0.1.1

dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  test: ^1.24.0
