name: smf_contribution_engine
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^7.5.9
  dart_style: ^3.1.0
  path: ^1.9.1
  mustachex: ^1.0.0
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
