name: smf_contribution_engine
description: Engine for structured code transformations in Dart/Flutter (insert/replace widgets, modify arguments, lists and classes).
version: 0.1.0
repository: https://github.com/saymyframe/smf_modules
homepage: https://saymyframe.com
issue_tracker: https://github.com/saymyframe/smf_modules/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.5.9
  dart_style: ^3.1.0
  path: ^1.9.1
  mustachex: ^1.0.0
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
