name: smf_firebase_crashlytics
description: Say My Frame firebase crashlytics.
version: 0.0.1
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, firebase, crashlytics]
license: Apache-2.0

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  smf_contracts: ^0.2.0
  smf_contribution_engine: ^0.2.0
  mason: ^0.1.1

dev_dependencies:
  lints: ">=5.0.0 <7.0.0"
  test: ^1.25.6
