name: smf_home_flutter
description: Home feature module (starter screen) for SMF Flutter applications.
version: 0.1.0
homepage: https://saymyframe.com
repository: https://github.com/saymyframe/smf_modules
issue_tracker: https://github.com/saymyframe/smf_modules/issues
topics: [flutter, template, boilerplate, feature, home-screen]

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  smf_contracts:
    path: ../../smf_contracts

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
