name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  call-reusable:
    uses: saymyframe/.github/.github/workflows/auto-assign.yml@main
    with:
      assignees: ybeshkarov
